<a href="https://colab.research.google.com/github/joelhrtl/DataAnalysis/blob/main/Job_Admission_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Machine Learning  - Logistic Regression

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

import statsmodels.api as sm

In [ ]:
# upload excel file
from google.colab import files
uploaded = files.upload()

Saving JOB_Admission.xlsx to JOB_Admission.xlsx

In [ ]:
# read excel file
import pandas as pd
df=pd.read_excel('JOB_Admission.xlsx')
df

,age,exam_score,experience,degree,extracurricular,internships,accepted
0,52,51,0,PhD,4,4,0
1,57,51,4,PhD,8,1,0
2,50,54,2,NaN,4,2,0
3,25,50,5,Master,0,2,0
4,56,58,4,Bachelor,2,2,0
...,...,...,...,...,...,...,...
95,37,92,15,Master,8,3,1
96,19,94,8,NaN,4,4,1
97,25,90,19,Master,9,2,1
98,28,98,6,NaN,9,3,1
99,26,98,17,NaN,7,1,1

In [ ]:
#check missing values
df.isnull().sum()

age                 0
exam_score          0
experience          0
degree             28
extracurricular     0
internships         0
accepted            0
dtype: int64

In [ ]:
df.shape

(100, 7)

In [ ]:
# Clean degree column by replace missing values by the mode
df['degree'] = df['degree'].fillna(df['degree'].mode()[0])
df.isna().sum()

age                0
exam_score         0
experience         0
degree             0
extracurricular    0
internships        0
accepted           0
dtype: int64

In [ ]:
df.columns

Index(['age', 'exam_score', 'experience', 'degree', 'extracurricular',
       'internships', 'accepted'],
      dtype='object')

In [ ]:
# SELECT X  FUTURES
X=df[['age', 'exam_score', 'experience', 'degree', 'extracurricular',
       'internships', 'accepted']]
X.head()

,age,exam_score,experience,degree,extracurricular,internships,accepted
0,52,51,0,PhD,4,4,0
1,57,51,4,PhD,8,1,0
2,50,54,2,PhD,4,2,0
3,25,50,5,Master,0,2,0
4,56,58,4,Bachelor,2,2,0

In [ ]:
#SELECT TARGET
X ["degree"]

#Convert
X ["degree"] = X["degree"].map({'PhD' : 3, 'Master' : 2, 'Bachelor' : 1 })

#Check result
X

,age,exam_score,experience,degree,extracurricular,internships,accepted
0,52,51,0,3,4,4,0
1,57,51,4,3,8,1,0
2,50,54,2,3,4,2,0
3,25,50,5,2,0,2,0
4,56,58,4,1,2,2,0
...,...,...,...,...,...,...,...
95,37,92,15,2,8,3,1
96,19,94,8,3,4,4,1
97,25,90,19,2,9,2,1
98,28,98,6,3,9,3,1
99,26,98,17,3,7,1,1